/*
 * Testbench: mac_array
 *
 * Description: Comprehensive functional verification testbench covering
 *              6 test scenarios: known-answer small K, identity multiplication,
 *              INT8 boundary values, accumulator stress (large K),
 *              zero inputs, and single-step outer product (K=1).
 * Author:      Generated by Vitis HLS Automation Environment
 */

#include <iostream>
#include <cstdlib>
#include <cstring>
#include "../src/mac_array.hpp"

// ============================================================
// Test Utilities
// ============================================================
static int error_count = 0;
static int test_count  = 0;

void check_result(const char* test_name, int r, int c,
                  int32_t actual, int32_t expected) {
    test_count++;
    if (actual != expected) {
        std::cerr << "[FAIL] " << test_name
                  << " C[" << r << "][" << c << "]"
                  << " -- expected: " << expected
                  << ", got: " << actual << std::endl;
        error_count++;
    }
}

// ============================================================
// Helper: Pack 4 x INT8 into a 32-bit word
// ============================================================
// Byte layout: [3]=val[3], [2]=val[2], [1]=val[1], [0]=val[0]
ap_uint<32> pack_4x_int8(int8_t v0, int8_t v1, int8_t v2, int8_t v3) {
    ap_uint<32> word;
    word( 7,  0) = (ap_uint<8>)(uint8_t)v0;
    word(15,  8) = (ap_uint<8>)(uint8_t)v1;
    word(23, 16) = (ap_uint<8>)(uint8_t)v2;
    word(31, 24) = (ap_uint<8>)(uint8_t)v3;
    return word;
}

// ============================================================
// Helper: Run one MAC invocation through the DUT and compare
// ============================================================
// A[ROWS][K], B[K][COLS] stored as plain int8_t arrays (row-major)
// expected_C[ROWS][COLS] as int32_t
void run_mac_test(
    const char* test_name,
    int K,
    const int8_t* A,       // A[ROWS][K] row-major
    const int8_t* B,       // B[K][COLS] row-major
    const int32_t* expected_C  // C[ROWS][COLS] row-major
) {
    std::cout << "--- " << test_name << " (K=" << K << ") ---" << std::endl;

    // Set up HLS streams
    hls::stream<axis32_t> act_in("act_in");
    hls::stream<axis32_t> weight_in("weight_in");
    hls::stream<axis32_t> result_out("result_out");

    // Fill input streams: K words each
    // act_in word k: pack A[0][k], A[1][k], A[2][k], A[3][k]
    //   (column k of A, one row value per byte)
    // weight_in word k: pack B[k][0], B[k][1], B[k][2], B[k][3]
    //   (row k of B)
    for (int k = 0; k < K; k++) {
        // Activations: column k of A (rows 0..3)
        int8_t a0 = A[0 * K + k];
        int8_t a1 = A[1 * K + k];
        int8_t a2 = A[2 * K + k];
        int8_t a3 = A[3 * K + k];

        axis32_t act_pkt;
        act_pkt.data = pack_4x_int8(a0, a1, a2, a3);
        act_pkt.keep = 0xF;
        act_pkt.strb = 0xF;
        act_pkt.last = (k == K - 1) ? 1 : 0;
        act_in.write(act_pkt);

        // Weights: row k of B (cols 0..3)
        int8_t w0 = B[k * COLS + 0];
        int8_t w1 = B[k * COLS + 1];
        int8_t w2 = B[k * COLS + 2];
        int8_t w3 = B[k * COLS + 3];

        axis32_t wt_pkt;
        wt_pkt.data = pack_4x_int8(w0, w1, w2, w3);
        wt_pkt.keep = 0xF;
        wt_pkt.strb = 0xF;
        wt_pkt.last = (k == K - 1) ? 1 : 0;
        weight_in.write(wt_pkt);
    }

    // Call DUT
    mac_array(act_in, weight_in, result_out, (kdim_t)K);

    // Read and compare 16 output words (row-major)
    int test_errors = 0;
    bool tlast_seen = false;
    int tlast_index = -1;

    for (int i = 0; i < ROWS * COLS; i++) {
        if (result_out.empty()) {
            std::cerr << "[FAIL] " << test_name
                      << " -- output stream empty at word " << i << std::endl;
            error_count++;
            test_errors++;
            break;
        }
        axis32_t out_pkt = result_out.read();

        // Read as signed INT32
        int32_t actual = (int32_t)(ap_int<32>)out_pkt.data;
        int r = i / COLS;
        int c = i % COLS;

        check_result(test_name, r, c, actual, expected_C[r * COLS + c]);
        if (actual != expected_C[r * COLS + c]) test_errors++;

        // Track TLAST
        if (out_pkt.last == 1) {
            tlast_seen = true;
            tlast_index = i;
        }
    }

    // Verify TLAST was on the last word (index 15)
    test_count++;
    if (!tlast_seen) {
        std::cerr << "[FAIL] " << test_name << " -- TLAST never asserted" << std::endl;
        error_count++;
        test_errors++;
    } else if (tlast_index != ROWS * COLS - 1) {
        std::cerr << "[FAIL] " << test_name << " -- TLAST at index " << tlast_index
                  << ", expected " << (ROWS * COLS - 1) << std::endl;
        error_count++;
        test_errors++;
    }

    // Verify no extra output
    test_count++;
    if (!result_out.empty()) {
        std::cerr << "[FAIL] " << test_name << " -- extra data in output stream" << std::endl;
        error_count++;
        test_errors++;
    }

    if (test_errors == 0) {
        std::cout << "[PASS] " << test_name << std::endl;
    } else {
        std::cout << "[INFO] " << test_name << " -- " << test_errors << " errors" << std::endl;
    }
}

// ============================================================
// Golden reference: compute C = A x B (plain C++)
// ============================================================
void golden_matmul(int K, const int8_t* A, const int8_t* B, int32_t* C) {
    for (int r = 0; r < ROWS; r++) {
        for (int c = 0; c < COLS; c++) {
            int32_t acc = 0;
            for (int k = 0; k < K; k++) {
                acc += (int32_t)A[r * K + k] * (int32_t)B[k * COLS + c];
            }
            C[r * COLS + c] = acc;
        }
    }
}

// ============================================================
// Test 1: Known-Answer -- Small K
// ============================================================
void test_known_answer() {
    const int K = 4;

    // A = [[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]
    int8_t A[ROWS * K] = {
         1,  2,  3,  4,
         5,  6,  7,  8,
         9, 10, 11, 12,
        13, 14, 15, 16
    };

    // B = [[1,5,9,13],[2,6,10,14],[3,7,11,15],[4,8,12,16]]
    // (transpose of A for a nice symmetric result)
    int8_t B[K * COLS] = {
         1,  5,  9, 13,
         2,  6, 10, 14,
         3,  7, 11, 15,
         4,  8, 12, 16
    };

    // Compute golden reference
    int32_t expected_C[ROWS * COLS];
    golden_matmul(K, A, B, expected_C);

    // Hand-verify one element: C[0][0] = 1*1+2*2+3*3+4*4 = 1+4+9+16 = 30
    if (expected_C[0] != 30) {
        std::cerr << "[SANITY] Golden model error: C[0][0]=" << expected_C[0]
                  << ", expected 30" << std::endl;
    }

    run_mac_test("Test1_KnownAnswer", K, A, B, expected_C);
}

// ============================================================
// Test 2: Identity Multiplication
// ============================================================
void test_identity() {
    const int K = 4;

    // A = [[10,20,30,40],[50,60,70,80],[1,2,3,4],[5,6,7,8]]
    int8_t A[ROWS * K] = {
        10, 20, 30, 40,
        50, 60, 70, 80,
         1,  2,  3,  4,
         5,  6,  7,  8
    };

    // B = identity matrix (4x4)
    int8_t B[K * COLS] = {
        1, 0, 0, 0,
        0, 1, 0, 0,
        0, 0, 1, 0,
        0, 0, 0, 1
    };

    // C = A * I = A, but as 32-bit sums of rows...
    // Actually C[r][c] = sum_k A[r][k] * I[k][c] = A[r][c]
    int32_t expected_C[ROWS * COLS];
    golden_matmul(K, A, B, expected_C);

    // Verify: C[0][0] should be A[0][0] = 10
    if (expected_C[0] != 10) {
        std::cerr << "[SANITY] Golden model error: C[0][0]=" << expected_C[0]
                  << ", expected 10" << std::endl;
    }

    run_mac_test("Test2_Identity", K, A, B, expected_C);
}

// ============================================================
// Test 3: Boundary Values -- INT8 Extremes
// ============================================================
void test_boundary_values() {
    const int K = 1;

    // Test 3a: all activations = 127, all weights = 127
    {
        int8_t A[ROWS * K];
        int8_t B[K * COLS];
        for (int i = 0; i < ROWS * K; i++) A[i] = 127;
        for (int i = 0; i < K * COLS; i++) B[i] = 127;

        int32_t expected_C[ROWS * COLS];
        // Each C[r][c] = 127 * 127 = 16129
        for (int i = 0; i < ROWS * COLS; i++) expected_C[i] = 16129;

        run_mac_test("Test3a_PosPos", K, A, B, expected_C);
    }

    // Test 3b: all activations = -128, all weights = 127
    {
        int8_t A[ROWS * K];
        int8_t B[K * COLS];
        for (int i = 0; i < ROWS * K; i++) A[i] = -128;
        for (int i = 0; i < K * COLS; i++) B[i] = 127;

        int32_t expected_C[ROWS * COLS];
        // Each C[r][c] = -128 * 127 = -16256
        for (int i = 0; i < ROWS * COLS; i++) expected_C[i] = -16256;

        run_mac_test("Test3b_NegPos", K, A, B, expected_C);
    }

    // Test 3c: all activations = -128, all weights = -128
    {
        int8_t A[ROWS * K];
        int8_t B[K * COLS];
        for (int i = 0; i < ROWS * K; i++) A[i] = -128;
        for (int i = 0; i < K * COLS; i++) B[i] = -128;

        int32_t expected_C[ROWS * COLS];
        // Each C[r][c] = -128 * -128 = 16384
        for (int i = 0; i < ROWS * COLS; i++) expected_C[i] = 16384;

        run_mac_test("Test3c_NegNeg", K, A, B, expected_C);
    }
}

// ============================================================
// Test 4: Accumulator Stress -- Large K
// ============================================================
void test_accumulator_stress() {
    const int K = 4096;

    int8_t* A = new int8_t[ROWS * K];
    int8_t* B = new int8_t[K * COLS];

    // All activations = 127, all weights = 127
    for (int i = 0; i < ROWS * K; i++) A[i] = 127;
    for (int i = 0; i < K * COLS; i++) B[i] = 127;

    // Each C[r][c] = 4096 * 127 * 127 = 4096 * 16129 = 66,064,384
    int32_t expected_C[ROWS * COLS];
    for (int i = 0; i < ROWS * COLS; i++) expected_C[i] = 66064384;

    run_mac_test("Test4_AccStress_K4096", K, A, B, expected_C);

    delete[] A;
    delete[] B;
}

// ============================================================
// Test 5: Zero Inputs
// ============================================================
void test_zero_inputs() {
    const int K = 8;

    int8_t A[ROWS * K];
    int8_t B[K * COLS];

    // All activations = 0
    std::memset(A, 0, ROWS * K);
    // Weights = arbitrary nonzero values
    for (int i = 0; i < K * COLS; i++) B[i] = (int8_t)((i % 256) - 128);

    // All outputs should be 0
    int32_t expected_C[ROWS * COLS];
    std::memset(expected_C, 0, sizeof(expected_C));

    run_mac_test("Test5_ZeroInputs", K, A, B, expected_C);
}

// ============================================================
// Test 6: Single Step (K=1) -- Outer Product
// ============================================================
void test_single_step() {
    const int K = 1;

    // act = {1, 2, 3, 4}
    int8_t A[ROWS * K] = {1, 2, 3, 4};

    // wt = {10, 20, 30, 40}
    int8_t B[K * COLS] = {10, 20, 30, 40};

    // C[r][c] = act[r] * wt[c] (outer product)
    int32_t expected_C[ROWS * COLS] = {
         10,  20,  30,  40,
         20,  40,  60,  80,
         30,  60,  90, 120,
         40,  80, 120, 160
    };

    run_mac_test("Test6_SingleStep_K1", K, A, B, expected_C);
}

// ============================================================
// Main
// ============================================================
int main() {
    std::cout << "==========================================" << std::endl;
    std::cout << "  Testbench: mac_array" << std::endl;
    std::cout << "==========================================" << std::endl;

    test_known_answer();
    test_identity();
    test_boundary_values();
    test_accumulator_stress();
    test_zero_inputs();
    test_single_step();

    std::cout << "==========================================" << std::endl;
    std::cout << "  Results: " << (test_count - error_count) << "/" << test_count
              << " passed" << std::endl;
    if (error_count == 0) {
        std::cout << "  *** ALL TESTS PASSED ***" << std::endl;
    } else {
        std::cout << "  *** " << error_count << " TEST(S) FAILED ***" << std::endl;
    }
    std::cout << "==========================================" << std::endl;

    return error_count;
}
