/*
 * cic_decimator — HLS IP Implementation
 *
 * Description: 4-stage CIC decimation filter, N=4 R=16 M=1
 *              AXI-Stream 16-bit signed I/O, ap_ctrl_none free-running.
 *
 * Architecture:
 *   Input -> [Integrator x4] -> Decimate /16 -> [Comb x4] -> Bit-prune -> Output
 *
 *   All arithmetic is modular (no saturation) as required by CIC theory.
 *   The comb section fires only on the decimated sample (count == 15).
 *   TLAST is the logical OR of all R=16 input TLASTs within a decimation block.
 *
 * Author:      Generated by Vitis HLS Automation Environment
 */

#include "cic_decimator.hpp"

// ============================================================
// Top-Level Function
// ============================================================
void cic_decimator(
    hls::stream<axis_din_t>& din,
    hls::stream<axis_dout_t>& dout
) {
    // ---- Interface Pragmas ----
    // ap_ctrl_none: free-running, no block-level handshake signals
    #pragma HLS INTERFACE ap_ctrl_none port=return

    // AXI-Stream interfaces for data in / data out
    #pragma HLS INTERFACE axis port=din
    #pragma HLS INTERFACE axis port=dout

    // Pipeline the function body at II=1 using the flip-flop (flp) style so
    // that each call processes exactly one input sample with no bubbles.
    #pragma HLS PIPELINE II=1 style=flp

    // ---- Static State (persists across invocations) ----
    // Integrator registers: 4 stages, each 32-bit modular accumulator
    static acc_t integrator[CIC_N];
    #pragma HLS ARRAY_PARTITION variable=integrator type=complete

    // Comb delay-line registers (M=1): one sample delay per stage
    static acc_t comb_delay[CIC_N];
    #pragma HLS ARRAY_PARTITION variable=comb_delay type=complete

    // Decimation counter: counts 0..R-1 (R=16 fits in 4 bits)
    static ap_uint<4> count = 0;

    // TLAST accumulator: OR of all TLASTs in the current R-sample block
    static ap_uint<1> tlast_or = 0;

    // ---- Read one AXI-Stream input sample ----
    axis_din_t in_pkt = din.read();

    // Sign-extend 16-bit input to 32-bit accumulator width
    acc_t sample = (acc_t)(din_t)in_pkt.data;

    // Accumulate TLAST across the R-sample decimation block
    tlast_or = tlast_or | (ap_uint<1>)in_pkt.last;

    // ---- Integrator Chain (runs every input sample) ----
    // 4 cascaded integrators; arithmetic is modular (wraps on overflow).
    // Loop is fully unrolled so all four accumulations execute in parallel.
    INTEG_STAGES:
    for (int i = 0; i < CIC_N; i++) {
        #pragma HLS UNROLL
        if (i == 0) {
            integrator[0] = integrator[0] + sample;
        } else {
            integrator[i] = integrator[i] + integrator[i - 1];
        }
    }

    // ---- Decimation: fire comb chain only every R samples ----
    bool decimate = (count == (ap_uint<4>)(CIC_R - 1));

    if (decimate) {
        // ---- Comb Chain (runs at 1/R rate) ----
        // 4 cascaded first-difference sections (M=1 differential delay).
        // Each stage: output = current_input - previous_input.
        // Arithmetic remains modular.
        acc_t comb_in  = integrator[CIC_N - 1]; // input to comb chain
        acc_t comb_out = 0;

        COMB_STAGES:
        for (int i = 0; i < CIC_N; i++) {
            #pragma HLS UNROLL
            comb_out      = comb_in - comb_delay[i];
            comb_delay[i] = comb_in;
            comb_in       = comb_out;
        }

        // ---- Bit Pruning with Rounding ----
        // The CIC gain for N=4, R=16, M=1 is (R*M)^N = 16^4 = 65536 = 2^16.
        // The 32-bit accumulator holds the scaled result; the top 16 bits are
        // the desired output.  Round by adding 0.5 LSB (1 << (PRUNE_BITS-1))
        // before arithmetic right-shifting by PRUNE_BITS.
        acc_t rounded  = comb_out + (acc_t)(1 << (PRUNE_BITS - 1));
        dout_t pruned  = (dout_t)(rounded >> PRUNE_BITS);

        // ---- Pack and Write Output AXI-Stream Packet ----
        axis_dout_t out_pkt;
        out_pkt.data = (ap_uint<16>)pruned;
        out_pkt.keep = 0x3;   // 2-byte word: both bytes valid
        out_pkt.strb = 0x3;
        out_pkt.last = tlast_or;

        dout.write(out_pkt);

        // ---- Reset Decimation State ----
        tlast_or = 0;
        count    = 0;
    } else {
        // No output this cycle; advance counter
        count = count + (ap_uint<4>)1;
    }
}
