/*
 * cic_decimator — HLS IP Header
 *
 * Description: 4-stage CIC decimation filter, N=4 R=16 M=1
 *              AXI-Stream 16-bit signed I/O, ap_ctrl_none free-running.
 *              32-bit modular accumulators with bit-pruning on output.
 * Author:      Generated by Vitis HLS Automation Environment
 */

#ifndef CIC_DECIMATOR_HPP
#define CIC_DECIMATOR_HPP

// ============================================================
// Vitis HLS Includes
// ============================================================
#include <ap_int.h>
#include <ap_axi_sdata.h>
#include <hls_stream.h>

// ============================================================
// Constants
// ============================================================
const int CIC_N      = 4;   // Number of integrator / comb stages
const int CIC_R      = 16;  // Decimation ratio
const int CIC_M      = 1;   // Differential delay (fixed at 1)
const int DIN_W      = 16;  // Input word width (bits)
const int DOUT_W     = 16;  // Output word width (bits)
const int ACC_W      = 32;  // Internal accumulator width (bits)
const int PRUNE_BITS = 16;  // Bits pruned (shift right before output)

// ============================================================
// Type Definitions
// ============================================================
typedef ap_int<16>  din_t;   // 16-bit signed input sample
typedef ap_int<16>  dout_t;  // 16-bit signed output sample
typedef ap_int<32>  acc_t;   // 32-bit signed accumulator (modular)

// AXI-Stream packet types — only used at top-level ports
typedef ap_axiu<16, 0, 0, 0> axis_din_t;
typedef ap_axiu<16, 0, 0, 0> axis_dout_t;

// ============================================================
// Top Function Prototype
// ============================================================
void cic_decimator(
    hls::stream<axis_din_t>& din,
    hls::stream<axis_dout_t>& dout
);

#endif // CIC_DECIMATOR_HPP
