/*
 * mac_array -- HLS IP Header
 *
 * Description: 4x4 output-stationary MAC array for INT8 deep learning
 *              inference. Computes C_tile[4][4] += A_tile[4][K] x B_tile[K][4]
 *              using 16 parallel processing elements.
 * Author:      Generated by Vitis HLS Automation Environment
 */

#ifndef MAC_ARRAY_HPP
#define MAC_ARRAY_HPP

// ============================================================
// Vitis HLS Includes
// ============================================================
#include <ap_int.h>
#include <hls_stream.h>
#include <ap_axi_sdata.h>

// ============================================================
// Constants
// ============================================================
const int ROWS  = 4;     // PE array rows (activation/output M-tile dimension)
const int COLS  = 4;     // PE array columns (weight/output N-tile dimension)
const int MAX_K = 4096;  // Maximum inner dimension

// ============================================================
// Type Definitions
// ============================================================

// AXI-Stream element type (top-level ports only)
typedef ap_axiu<32, 0, 0, 0> axis32_t;

// Core data types
typedef ap_int<8>   act_t;     // INT8 activation [-128, 127]
typedef ap_int<8>   weight_t;  // INT8 weight [-128, 127]
typedef ap_int<32>  acc_t;     // 32-bit accumulator (sufficient for K<=4096)
typedef ap_uint<16> kdim_t;    // Inner dimension parameter

// ============================================================
// Top Function Prototype
// ============================================================
void mac_array(
    hls::stream<axis32_t>& act_in,
    hls::stream<axis32_t>& weight_in,
    hls::stream<axis32_t>& result_out,
    kdim_t k_dim
);

#endif // MAC_ARRAY_HPP
