/*
 * mac_array -- HLS IP Implementation
 *
 * Description: 4x4 output-stationary MAC array for INT8 deep learning
 *              inference. Processes one tile per invocation:
 *              C_tile[4][4] += A_tile[4][K] x B_tile[K][4].
 *
 *              Compute phase: K cycles at II=1, 16 parallel MACs.
 *              Drain phase:   16 cycles, output row-major with TLAST.
 *
 * Author:      Generated by Vitis HLS Automation Environment
 */

#include "mac_array.hpp"

// ============================================================
// Top-Level Function
// ============================================================
void mac_array(
    hls::stream<axis32_t>& act_in,
    hls::stream<axis32_t>& weight_in,
    hls::stream<axis32_t>& result_out,
    kdim_t k_dim
) {
    // ---- Interface Pragmas ----
    #pragma HLS INTERFACE axis port=act_in        // Streaming packed activations (4xINT8)
    #pragma HLS INTERFACE axis port=weight_in     // Streaming packed weights (4xINT8)
    #pragma HLS INTERFACE axis port=result_out    // Streaming INT32 results
    #pragma HLS INTERFACE s_axilite port=k_dim  bundle=ctrl  // Inner dimension K
    #pragma HLS INTERFACE s_axilite port=return bundle=ctrl  // Block-level control (ap_ctrl_hs)

    // ---- Accumulator array: 4x4 = 16 PEs ----
    // Reset to zero each invocation (stateless design)
    acc_t acc[ROWS][COLS];
    #pragma HLS ARRAY_PARTITION variable=acc complete dim=0

    INIT_ROW:
    for (int r = 0; r < ROWS; r++) {
        #pragma HLS UNROLL
        INIT_COL:
        for (int c = 0; c < COLS; c++) {
            #pragma HLS UNROLL
            acc[r][c] = 0;
        }
    }

    // ---- Compute Phase: K cycles, 16 parallel MACs per cycle ----
    COMPUTE_K:
    for (int k = 0; k < k_dim; k++) {
        #pragma HLS PIPELINE II=1
        #pragma HLS LOOP_TRIPCOUNT min=1 max=4096

        // Read one packed activation word and one packed weight word
        axis32_t act_word = act_in.read();
        axis32_t wt_word  = weight_in.read();

        // Unpack 4 x INT8 activations from 32-bit word
        // Byte layout: [3]=row3, [2]=row2, [1]=row1, [0]=row0
        act_t a[ROWS];
        #pragma HLS ARRAY_PARTITION variable=a complete
        UNPACK_ACT:
        for (int r = 0; r < ROWS; r++) {
            #pragma HLS UNROLL
            a[r] = (act_t)act_word.data(r * 8 + 7, r * 8);
        }

        // Unpack 4 x INT8 weights from 32-bit word
        // Byte layout: [3]=col3, [2]=col2, [1]=col1, [0]=col0
        weight_t w[COLS];
        #pragma HLS ARRAY_PARTITION variable=w complete
        UNPACK_WT:
        for (int c = 0; c < COLS; c++) {
            #pragma HLS UNROLL
            w[c] = (weight_t)wt_word.data(c * 8 + 7, c * 8);
        }

        // 16 parallel multiply-accumulate operations (fully unrolled)
        MAC_ROW:
        for (int r = 0; r < ROWS; r++) {
            #pragma HLS UNROLL
            MAC_COL:
            for (int c = 0; c < COLS; c++) {
                #pragma HLS UNROLL
                acc[r][c] += (acc_t)a[r] * (acc_t)w[c];
            }
        }
    }

    // ---- Drain Phase: output 16 INT32 results row-major ----
    DRAIN_ROW:
    for (int r = 0; r < ROWS; r++) {
        DRAIN_COL:
        for (int c = 0; c < COLS; c++) {
            #pragma HLS PIPELINE II=1

            axis32_t out_word;
            out_word.data = acc[r][c];
            out_word.keep = 0xF;   // All 4 bytes valid
            out_word.strb = 0xF;
            // Assert TLAST on the final word (row 3, col 3)
            out_word.last = (r == ROWS - 1 && c == COLS - 1) ? 1 : 0;
            result_out.write(out_word);
        }
    }
}
